name: PHPStan Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      # Create .env file from secrets
      - name: Create .env file
        run: |
          echo "APP_ENV=test" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        
      # Install Composer dependencies
      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Warm up Symfony cache
        run: php bin/console cache:warmup --env=test

      # Run PHPStan
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=512M
